//
//  LanguageListWireframe.swift
//  SBBOLtest
//
//  Created by Erik Vildanov on 30/05/2019.
//  Copyright (c) 2019 Erik Vildanov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LanguageListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "LanguageList", bundle: nil)

    // MARK: - Module setup -

    init(language: String, isSource: Bool) {
        let moduleViewController = storyboard.instantiateViewController(ofType: LanguageListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = LanguageListInteractor()
        let presenter = LanguageListPresenter(view: moduleViewController, interactor: interactor, wireframe: self, language: language, isSource: isSource)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LanguageListWireframe: LanguageListWireframeInterface {
    func navigate(to option: LanguageListNavigationOption) {
        switch option {
        case .close:
            navigationController?.dismiss(animated: true, completion: nil)
        }
    }
    
}
