//
//  WordListInteractor.swift
//  SBBOLtest
//
//  Created by Erik Vildanov on 30/05/2019.
//  Copyright (c) 2019 Erik Vildanov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WordListInteractor {
}

// MARK: - Extensions -

extension WordListInteractor: WordListInteractorInterface {
    func getAllHistory() -> [History] {
        return CoreDataManager.sharedInstance.fetchAllHistory() ?? []
    }
    
    func getFilterHistory(searchText: String) -> [History] {
        let filter = CoreDataManager.sharedInstance.fetchAllHistory()!.filter({ (text) -> Bool in
            
            let tmp: String = text.sourceText + text.translate
            let range = tmp.range(of: searchText, options: String.CompareOptions.caseInsensitive)
            return range != nil
        })
        
        return filter
    }
    
}
