//
//  TabBarInteractor.swift
//  SBBOLtest
//
//  Created by Erik Vildanov on 30/05/2019.
//  Copyright (c) 2019 Erik Vildanov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TabBarInteractor {
}

// MARK: - Extensions -

extension TabBarInteractor: TabBarInteractorInterface {
}
