//
//  TabBarPresenter.swift
//  SBBOLtest
//
//  Created by Erik Vildanov on 30/05/2019.
//  Copyright (c) 2019 Erik Vildanov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TabBarPresenter {

    // MARK: - Private properties -

    private unowned let view: TabBarViewInterface
    private let interactor: TabBarInteractorInterface
    private let wireframe: TabBarWireframeInterface

    // MARK: - Lifecycle -

    init(view: TabBarViewInterface, interactor: TabBarInteractorInterface, wireframe: TabBarWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    func viewDidLoad() {
        view.setViewSontrollers()
    }
}

// MARK: - Extensions -

extension TabBarPresenter: TabBarPresenterInterface {
    func removeAllHistory() {
        CoreDataManager.sharedInstance.deleteAllHistory()
    }
    
}
