//
//  SettingsInterfaces.swift
//  SBBOLtest
//
//  Created by Erik Vildanov on 30/05/2019.
//  Copyright (c) 2019 Erik Vildanov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SettingsWireframeInterface: WireframeInterface {
}

protocol SettingsViewInterface: ViewInterface {
}

protocol SettingsPresenterInterface: PresenterInterface {
}

protocol SettingsInteractorInterface: InteractorInterface {
}
