//
//  TranslateWireframe.swift
//  SBBOLtest
//
//  Created by Erik Vildanov on 30/05/2019.
//  Copyright (c) 2019 Erik Vildanov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TranslateWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Translate", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: TranslateViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = TranslateInteractor()
        let presenter = TranslatePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TranslateWireframe: TranslateWireframeInterface {
    
    func navigate(to option: TranslateNavigationOption) {
        switch option {
        case .openLangList(let lang, let isSource):
            presentWireframeWithNavigation(wireframe: LanguageListWireframe(language: lang, isSource: isSource))
        }
    }
    
    func presentWireframeWithNavigation(wireframe: BaseWireframe) {
        let nav = UINavigationController(rootViewController: wireframe.viewController)
        nav.navigationBar.barTintColor = .orange
        nav.navigationBar.tintColor = .black
        nav.navigationBar.isTranslucent = false
        navigationController?.present(nav, animated: true, completion: nil)
    }
    
}
